version: "3"

services:
  yarn:
    image: node:15.8.0
    user: node
    working_dir: /home/node
    entrypoint: yarn
    env_file: .env
    command: --help
    volumes:
      - .:/home/node

  bash:
    image: node:15.8.0
    user: node
    working_dir: /home/node
    entrypoint: bash
    env_file: .env
    volumes:
      - .:/home/node
